/* ui.js - the document: phases, step cards, the three buttons.
 *
 * One renderer, two pages. A MOP generated by mopgen.py and a workflow the
 * operator has just dropped into the runner are the same thing by the time
 * they get here - a node, a step list, the phase and loop tables, the seed
 * variables, the globals and the request parameters - so they must look and
 * behave identically.
 *
 *     initDocument({mount, meta, steps, phases, loops, vars, globals, params,
 *                   lint, pristine, seed, seedExtra, storageKey})
 *
 * The run itself - which step executes, what a failure routes to, which phase
 * a stop still lets through - is runtime.js. This file draws it and wires the
 * buttons. Every id the page exposes (btnDebug, btnExport, paramGrid, summary,
 * phases, and the data-set / data-custom / data-exit / data-status attributes)
 * is part of the contract test_page_dom.js drives.
 */

function initDocument(doc) {
  const mount = doc.mount || document.body;
  const META = doc.meta || {};
  const STEPS = doc.steps || [];
  const PHASES = doc.phases || [];
  const PARAMS = doc.params || {};
  const SEED = doc.seed || null;
  const KEY = (doc.storageKey || ("execflow:" + META.node + ":" + META.activity)) +
              (SEED && SEED.savedAt ? ":saved:" + SEED.savedAt : "");
  const RUNDOC = { steps: STEPS, phases: PHASES, loops: doc.loops || {}, vars: doc.vars || {},
                   globals: doc.globals || [], params: PARAMS };
  const PH = {};
  for (const p of PHASES) PH[p.key] = p;

  const blank = () => ({ choices: {}, custom: {}, exit: {}, status: {}, timeout: {}, params: {},
                         debug: false, validateChecks: false, strict: false, showHidden: false });
  let state = load() || (SEED && SEED.state ? JSON.parse(JSON.stringify(SEED.state)) : null) || blank();
  for (const k of ["choices", "custom", "exit", "status", "timeout", "params"]) state[k] = state[k] || {};

  function load() {
    try { return JSON.parse(localStorage.getItem(KEY) || "null"); } catch (e) { return null; }
  }
  function save() {
    try { localStorage.setItem(KEY, JSON.stringify(state)); } catch (e) { /* private mode */ }
  }

  /* ================================================================= *
   *  Run state
   * ================================================================= */
  let RESULT = null, OTHER = null, DIVERGE = null;

  function recompute() {
    RESULT = simulate(RUNDOC, state, { strict: !!state.strict });
    // The other reading of phase-level on_failure: stop, to say where the
    // intended rule and the engine as written part company. They can only
    // differ once something has failed.
    if (RESULT.summary.counts.failure) {
      OTHER = simulate(RUNDOC, state, { strict: !state.strict });
      DIVERGE = divergence(RUNDOC, state.strict ? OTHER : RESULT, state.strict ? RESULT : OTHER);
    } else {
      OTHER = null;
      DIVERGE = null;
    }
    for (const st of STEPS) st.rt = RESULT.rt[st.uid];
    state.vars = RESULT.vars;
    return RESULT.vars;
  }

  /* ================================================================= *
   *  Render
   * ================================================================= */
  const esc = s => String(s === undefined || s === null ? "" : s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

  const STATE_PILL = {
    success: ["p-ok", "SUCCESS"], warning: ["p-warn", "WARNING"], failure: ["p-bad", "FAILURE"],
    skipped: ["p-idle", "SKIPPED"], notrun: ["p-idle", "NOT EXECUTED"],
    pending: ["p-idle", "pending"], unknown: ["p-warn", "CONDITIONAL"],
  };
  const KIND = { rest: "REST", sftp: "SFTP", local: "local", email: "mail", remote: "" };

  mount.innerHTML =
    '<div class="toolbar">' +
      '<label class="chk" title="Walk the pre/post health checks the way the ' +
        'activity is walked - criteria, custom output and all - instead of ' +
        'ticking OK or NOK">' +
        '<input type="checkbox" id="chkValidateChecks"> Validate pre/post checks</label>' +
      '<label class="chk" title="Reproduce ExecutionOrchestrator exactly, including where a ' +
        'failure inside a loop never reaches the phase-level on_failure: stop">' +
        '<input type="checkbox" id="chkStrict"> Strict engine</label>' +
      '<label class="chk" title="Steps marked hide_when_skipped are hidden while skipped, as the engine ' +
        'leaves them out of its log">' +
        '<input type="checkbox" id="chkHidden"> Show hidden steps</label>' +
      '<button id="btnRestSuccess">Rest all Success</button>' +
      '<button id="btnDebug">Debug panels: off</button>' +
      '<button id="btnExpand">Expand all</button>' +
      '<button id="btnCollapse">Collapse all</button>' +
      '<button id="btnReset" class="ghost">Reset run</button>' +
      '<button id="btnExport" class="ghost">Export result JSON</button>' +
      '<button id="btnReport" class="ghost">Export report</button>' +
      '<button id="btnSave" class="ghost">Save walked copy</button>' +
      '<span class="grow"></span><span class="sum" id="summary"></span>' +
    '</div>' +
    '<div id="banners"></div>' +
    '<div class="card" id="lintCard" style="display:none">' +
      '<h2 data-toggle="lintBody"><span class="grow">Template findings</span>' +
      '<span class="k" id="lintCount"></span></h2>' +
      '<div class="body hidden" id="lintBody"></div>' +
    '</div>' +
    '<div class="card" id="paramCard">' +
      '<h2 data-toggle="paramBody"><span class="grow">Request parameters</span>' +
      '<span class="k" id="paramCount"></span></h2>' +
      '<div class="body" id="paramBody"><div class="grid" id="paramGrid"></div>' +
      '<div class="k" style="margin-top:8px">Changing a value re-resolves every ' +
      'command below. Values the CIQ supplies are not listed here, nor are ' +
      'values a step sets while the workflow runs.</div></div>' +
    '</div>' +
    '<div id="phases"></div>';

  const $ = id => mount.querySelector("#" + id);

  function renderLint() {
    const findings = doc.lint || [];
    if (!findings.length) return;
    $("lintCard").style.display = "";
    const errors = findings.filter(f => f.severity === "error").length;
    $("lintCount").textContent = findings.length + " finding" + (findings.length === 1 ? "" : "s") +
      (errors ? ", " + errors + " error" + (errors === 1 ? "" : "s") : "");
    $("lintBody").innerHTML = '<ul class="lint">' + findings.map(f =>
      '<li class="' + esc(f.severity) + '"><b>' + esc(f.severity.toUpperCase()) + '</b> ' +
      '<span class="mono">' + esc(f.rule) + '</span> ' + esc(f.message) +
      (f.where ? ' <span class="k">' + esc(f.where) + '</span>' : "") + '</li>').join("") + '</ul>';
  }

  function renderParams() {
    const grid = $("paramGrid");
    const used = {};
    for (const st of STEPS) for (const t of st.consumes || []) used[t] = (used[t] || 0) + 1;
    const names = Object.keys(PARAMS).concat(
      Object.keys(state.params).filter(k => !(k in PARAMS)));
    const extra = [];
    for (const st of STEPS) for (const u of st.unresolved || []) {
      if (u.runtime) continue;                  // a step sets it; nothing to fill in
      if (!names.includes(u.token) && !extra.includes(u.token) &&
          u.token.indexOf(".") < 0 && u.token.indexOf("base64:") < 0) extra.push(u.token);
    }
    const all = names.concat(extra);
    $("paramCount").textContent = all.length + " parameter" + (all.length === 1 ? "" : "s") +
      (extra.length ? ", " + extra.length + " unresolved" : "");
    grid.innerHTML = all.map(n => {
      const v = (n in state.params) ? state.params[n] : (PARAMS[n] !== undefined ? PARAMS[n] : "");
      const hits = used[n] ? (" · " + used[n] + " step" + (used[n] === 1 ? "" : "s")) : "";
      const miss = !v && extra.includes(n) ? ' class="f unres"' : ' class="f"';
      return '<div><label' + miss + '>' + esc(n) + esc(hits) + '</label>' +
             '<input type="text" data-param="' + esc(n) + '" value="' + esc(v) + '"></div>';
    }).join("");
    grid.querySelectorAll("input[data-param]").forEach(inp => {
      inp.addEventListener("change", () => {
        state.params[inp.getAttribute("data-param")] = inp.value;
        save(); draw();
      });
    });
  }

  function renderBanners() {
    const out = [];
    const s = RESULT.summary;
    if (s.stoppedAt) {
      out.push('<div class="banner bad"><b>The run stops at ' + esc(s.stoppedAt) + '.</b> ' +
               'Later steps in that phase and later phases are NOT EXECUTED; a rollback phase ' +
               'still runs if its when is true.</div>');
    }
    const rb = PHASES.filter(p => p.post_failure);
    if (rb.length) {
      const ran = rb.some(p => STEPS.some(st => st.phase === p.key &&
        ["success", "failure", "warning", "pending"].indexOf((st.rt || {}).state) >= 0));
      out.push('<div class="banner ' + (ran ? "warn" : "idle") + '">Rollback: ' +
               (ran ? "<b>runs</b>" : "does not run") + ' &middot; ROLLBACK_REQUIRED = <span class="mono">' +
               esc(s.engine.ROLLBACK_REQUIRED || '""') + '</span> &middot; ' +
               rb.map(p => esc(p.id) + ' when <span class="mono">' + esc(p.when || "(always)") + '</span>').join(", ") +
               '</div>');
    }
    if (DIVERGE) {
      const st = STEPS.find(x => x.uid === DIVERGE.uid) || {};
      const label = x => (STATE_PILL[x] || STATE_PILL.pending)[1];
      out.push('<div class="banner warn" id="divergeBanner"><b>Engine gap.</b> From step ' +
               esc(st.seq) + ' (' + esc(PH[st.phase] ? PH[st.phase].id : st.phase) + ') the intended rule says ' +
               '<b>' + label(DIVERGE.intended) + '</b> but ExecutionOrchestrator as written gives <b>' +
               label(DIVERGE.engine) + '</b>: a failure inside a loop never reaches the phase-level ' +
               'on_failure: stop in the engine (phaseHadAnyFailure is local to each loop body). ' +
               (state.strict ? 'You are viewing the engine as written.' : 'Tick <i>Strict engine</i> to see what the engine does.') +
               '</div>');
    }
    $("banners").innerHTML = out.join("");
  }

  function stepCard(st) {
    const rt = st.rt || {};
    const [cls, label] = STATE_PILL[rt.state] || STATE_PILL.pending;
    const open = state["open:" + st.uid] ? " open" : "";
    const choice = state.choices[st.uid] || "pending";
    const loop = (st.loop_path || []).map(l => l.label).filter(Boolean).join(" / ");
    const hidden = st.hide_when_skipped && rt.state === "skipped" && !state.showHidden;

    let h = '<div class="step s-' + rt.state + (hidden ? " hid" : "") + '" id="c' + st.uid + '">';
    h += '<div class="sh"><span class="seq">' + st.seq + '</span><div class="grow">';
    h += '<div class="sd">' + esc(rt.desc || st.description || st.uid) + '</div>';
    h += '<div class="meta">' + (KIND[st.kind] ? '<span class="kind">' + KIND[st.kind] + '</span> ' : "") +
         esc(st.node_target || st.node_ref || "local");
    if (st.step_id) h += ' &middot; <span class="mono">' + esc(st.step_id) + '</span>';
    if (loop) h += ' &middot; ' + esc(loop);
    if (st.when) h += ' &middot; when ' + esc(st.when);
    h += '</div></div><span class="pill ' + cls + '">' + label + '</span>';
    h += '<button class="ghost" data-toggle-step="' + st.uid + '">' +
         (open ? "hide" : "detail") + '</button>';
    h += '</div>';

    const cmd = rt.send || st.send;
    if (cmd) h += '<div class="cmdbox"><pre>' + esc(cmd) + '</pre>' +
                  (rt.body ? '<pre class="body">' + esc(rt.body) + '</pre>' : "") + '</div>';
    if (st.email) {
      h += '<div class="cmdbox"><pre>to: ' + esc(st.email.to) +
           '\nsubject: ' + esc(st.email.subject) + '</pre></div>';
    }
    if (rt.note) h += '<div class="note">' + esc(rt.note) + '</div>';
    for (const n of rt.notes || []) h += '<div class="note">' + esc(n) + '</div>';
    if ((rt.routes || []).length) {
      h += '<ul class="routes">' + rt.routes.map(r => '<li>' + esc(r) + '</li>').join("") + '</ul>';
    }
    if (rt.rerun) {
      const [rc, rl] = STATE_PILL[rt.rerun.state] || STATE_PILL.pending;
      h += '<div class="note">ran again later (then: / on_failure phase): <span class="pill ' + rc + '">' + rl + '</span></div>';
    }

    h += '<div class="btns">';
    h += btn(st.uid, "success", "Success", choice);
    h += btn(st.uid, "failure", "Failure", choice);
    h += btn(st.uid, "custom", "Custom input", choice);
    if (choice !== "pending") {
      h += '<button data-set="' + st.uid + ':pending" class="ghost">clear</button>';
    }
    h += '<button data-rest="' + st.uid + '" class="ghost" title="Mark this step ' +
         'and every one after it Success">Success from here</button>';
    h += '</div>';

    h += '<div class="sbody' + open + '" id="b' + st.uid + '">';
    if (choice === "custom") {
      const rest = st.kind === "rest";
      h += '<label class="f">' + (rest ? "Paste the response body" : "Paste what the node printed") + '</label>';
      h += '<textarea data-custom="' + st.uid + '">' + esc(state.custom[st.uid] || "") + '</textarea>';
      h += '<div class="btns" style="padding:8px 0 0;align-items:center">' +
           '<button data-eval="' + st.uid + '" class="primary">Evaluate</button>';
      if (rest) {
        const status = state.status[st.uid] === undefined ? String(st.success_status || 200)
                                                          : String(state.status[st.uid]);
        h += '<label class="f" style="margin:0 0 0 6px">HTTP status</label>' +
             '<input type="text" class="exit" data-status="' + st.uid + '" value="' + esc(status) + '">' +
             statusChips(st);
      } else {
        const code = state.exit[st.uid] === undefined ? "0" : String(state.exit[st.uid]);
        h += '<label class="f" style="margin:0 0 0 6px">exit code</label>' +
             '<input type="text" class="exit" data-exit="' + st.uid + '" value="' + esc(code) + '">' +
             '<span class="k">' + (st.ignore_exit ? "not read by the engine: this step completes on its prompt_regex"
                                                   : "what the command returned; 0 is success") + '</span>';
      }
      h += '<label class="chk k"><input type="checkbox" data-timeout="' + st.uid + '"' +
           (state.timeout[st.uid] ? " checked" : "") + '> ' +
           (rest ? "no response (connection error)" : "did not complete (timeout)") + '</label>';
      h += '</div>';
      h += verdictPanel(st, rt);
    } else if (choice !== "pending") {
      h += '<label class="f">Output used (' +
           (choice === "success" ? "synthesised from the success criteria"
                                 : "synthesised to fail the criteria") +
           (st.kind === "rest" ? ", HTTP " + esc(rt.completed === false ? "no response" : rt.status) : "") + ')</label>';
      h += '<pre>' + esc(rt.output || (rt.completed === false ? "(the command did not complete)"
                                                              : "(no output asserted - judged on exit code)")) + '</pre>';
      if (choice === "failure") h += verdictPanel(st, rt);
    }
    if (rt.messageText) h += '<div class="meta" style="margin-top:6px">' + esc(rt.messageText) + '</div>';

    if (state.debug) h += debugPanel(st, rt);
    h += '</div></div>';
    return h;
  }

  function statusChips(st) {
    const seen = [];
    const want = [st.success_status, st.failure_status, 200, 401, 404, 500];
    for (const s of want) if (s && seen.indexOf(s) < 0) seen.push(s);
    return seen.map(s => '<button class="ghost chip" data-status-set="' + st.uid + ':' + s + '">' + s + '</button>').join("");
  }

  /**
   * Why this step passed or failed, on the evidence given.
   *
   * `exit_code: 0` as the sole criterion is the one that catches people out:
   * any pasted text satisfies it, and without this panel the page just says
   * SUCCESS and looks broken.
   */
  function verdictPanel(st, rt) {
    const checks = rt.checks || [];
    const [cls, label] = STATE_PILL[rt.state] || STATE_PILL.pending;
    let h = '<div class="verdict"><div class="vhead"><span class="pill ' + cls + '">' +
            label + '</span> <span class="k">on the output' +
            (st.kind === "rest" ? ", HTTP status" : " and exit code") + ' you gave' +
            (rt.branch ? " - validation took the " + esc(rt.branch) + " branch" : "") + '</span></div>';
    h += '<ul class="checks">';
    if (rt.commandSuccess === false) {
      h += '<li class="bad">✗ the command itself failed (' + esc(rt.cause || "") + ') - ' +
           'the engine reads the failure branch</li>';
    }
    for (const check of checks) {
      h += '<li class="' + (check.ok ? "good" : "bad") + '">' +
           (check.ok ? "✓" : "✗") + " " + esc(check.label) +
           (check.detail ? ' <span class="k">(' + esc(check.detail) + ')</span>' : "");
      for (const t of check.trace || []) {
        h += '<div class="k">' + esc(t.expr) + " &nbsp; [" +
             esc(t.leftVal === null ? "<unset>" : t.leftVal) + "] vs [" + esc(t.right) +
             "] &rarr; " + (t.result ? "TRUE" : "FALSE") + "</div>";
      }
      for (const child of check.children || []) {
        h += '<div class="k">' + (child.ok ? "✓" : "✗") + " " +
             esc(child.label) + "</div>";
      }
      h += "</li>";
    }
    h += "</ul>";

    const captured = (rt.log || []).filter(l => l.value !== null && l.value !== undefined);
    const missed = (rt.log || []).filter(l => l.value === null || l.value === undefined);
    if (captured.length) {
      h += '<div class="k" style="margin-top:6px">set from your output: ' +
           captured.map(l => '<span class="mono">' + esc(l.name) + "=" + esc(l.value) +
                             "</span>").join(", ") + "</div>";
    }
    if (missed.length) {
      h += '<div class="k">nothing matched: ' +
           missed.map(l => '<span class="mono">' + esc(l.name) + "</span>").join(", ") + "</div>";
    }
    if (!(st.register || []).length && !(st.rest && (st.rest.response_template || []).length)) {
      h += '<div class="k" style="margin-top:6px">this step captures nothing from its ' +
           "output, so only whether the command succeeded decides it</div>";
    }
    return h + "</div>";
  }

  function btn(uid, kind, text, choice) {
    return '<button data-set="' + uid + ':' + kind + '"' +
           (choice === kind ? ' class="on"' : '') + '>' + text + '</button>';
  }

  function debugPanel(st, rt) {
    let h = '<div class="dbg"><b>debug</b>';
    h += row("phase", esc(st.phase) + " (" + esc(st.render_mode) + ")");
    if (st.step_id) h += row("step id", esc(st.step_id));
    if (st.node_ref !== st.node_target) h += row("node", esc(st.node_ref) + " &rarr; " + esc(st.node_target));
    if (st.send_raw && st.send_raw !== rt.send) h += row("send raw", esc(st.send_raw));
    for (const t of rt.trace || []) {
      h += row("condition", esc(t.expr) + " &nbsp; [" +
               esc(t.leftVal === null ? "<unset>" : t.leftVal) + "] vs [" + esc(t.right) +
               "] &rarr; <b>" + (t.result ? "TRUE" : "FALSE") + "</b>");
    }
    for (const u of st.unresolved || []) {
      h += row("unresolved", '<span class="unres">${' + esc(u.token) + '}</span> &mdash; ' + esc(u.reason));
    }
    for (const l of rt.log || []) {
      h += row("set", esc(l.name) + " = " +
               (l.value === null || l.value === undefined ? "<i>" + esc(l.source) + "</i>"
                                                          : esc(l.value) + ' <span class="k">' + esc(l.source) + '</span>'));
    }
    if ((st.consumes || []).length) h += row("consumes", (st.consumes || []).map(esc).join(", "));
    const crit = (st.validation || {}).successCriteria;
    if (crit && Object.keys(crit).length) h += row("criteria", esc(JSON.stringify(crit)));
    const bv = (st.validation || {}).branchVars || {};
    for (const b of ["success", "failure", "warning"]) {
      if (bv[b] && Object.keys(bv[b]).length) h += row(b + " vars", esc(JSON.stringify(bv[b])));
    }
    if (st.retries) h += row("retries", st.retries + " every " + (st.retry_delay_sec || 0) + "s");
    h += row("on_failure", esc(JSON.stringify(st.on_failure)));
    return h + '</div>';
  }
  function row(k, v) { return '<div class="row"><span>' + k + '</span><span>' + v + '</span></div>'; }

  function checklistTable(steps) {
    let h = '<table><thead><tr><th style="width:44px">#</th><th>Step</th>' +
            '<th>Command</th><th style="width:150px">Expected</th>' +
            '<th style="width:110px">Result</th></tr></thead><tbody>';
    for (const st of steps) {
      const rt = st.rt || {};
      const [cls, label] = STATE_PILL[rt.state] || STATE_PILL.pending;
      const hidden = st.hide_when_skipped && rt.state === "skipped" && !state.showHidden;
      h += '<tr' + (hidden ? ' class="hid"' : "") + '><td class="k">' + st.seq + '</td>';
      h += '<td>' + esc(rt.desc || st.description) + '<div class="k">' +
           esc(st.node_target || "") + '</div>' +
           (rt.note ? '<div class="k">' + esc(rt.note) + '</div>' : "") + '</td>';
      h += '<td class="cmd">' + esc(rt.send || st.send || (st.email ? "send mail" : "")) + '</td>';
      h += '<td class="k">' + esc((st.validation || {}).description || "") + '</td>';
      h += '<td><span class="pill ' + cls + '">' + label + '</span>' +
           '<div class="btns" style="padding:4px 0 0">' +
           '<button data-set="' + st.uid + ':success" class="' +
             (state.choices[st.uid] === "success" ? "on" : "") + '">OK</button>' +
           '<button data-set="' + st.uid + ':failure" class="' +
             (state.choices[st.uid] === "failure" ? "on" : "") + '">NOK</button>' +
           (state.choices[st.uid] ? '<button data-set="' + st.uid + ':pending" class="ghost">clear</button>' : "") +
           '</div></td></tr>';
    }
    return h + '</tbody></table>';
  }

  function phaseHeader(g) {
    const p = PH[g.phase] || {};
    const bits = [];
    if (p.on_failure) bits.push("on_failure: " + p.on_failure);
    if (p.post_failure) bits.push("runs after a stop");
    if ((p.then || []).length) bits.push("then: " + p.then.join(", "));
    if (p.when) bits.push("when " + p.when);
    return bits.length ? ' <span class="k">' + esc(bits.join(" · ")) + '</span>' : "";
  }

  function draw() {
    recompute();
    renderParams();
    renderBanners();

    const groups = [];
    for (const st of STEPS) {
      const last = groups[groups.length - 1];
      if (!last || last.phase !== st.phase) {
        groups.push({ phase: st.phase, name: st.phase_name,
                      description: st.phase_description, mode: st.render_mode, steps: [st] });
      } else last.steps.push(st);
    }

    $("phases").innerHTML = groups.map((g, i) => {
      const counts = {};
      for (const st of g.steps) {
        const s = (st.rt || {}).state || "pending";
        counts[s] = (counts[s] || 0) + 1;
      }
      const badge = Object.keys(counts).map(k => {
        const [cls, label] = STATE_PILL[k] || STATE_PILL.pending;
        return '<span class="pill ' + cls + '">' + counts[k] + ' ' + label + '</span>';
      }).join(" ");
      const bodyId = "ph" + i;
      // "Validate pre/post checks" promotes the checklist phases to the same
      // treatment the activity gets: real criteria, pasted output, the verdict
      // panel. OK/NOK is a faster read when the checks are a formality, and the
      // wrong tool when one of them is what the change hinges on.
      const mode = state.validateChecks ? "interactive" : g.mode;
      const gatedOff = g.steps.every(st => ((st.rt || {}).note || "").indexOf("phase ") === 0 &&
                                           (st.rt || {}).state === "skipped");
      return '<div class="card' + (gatedOff ? " gated" : "") + '" data-phase="' + esc(g.phase) + '">' +
        '<h2 data-toggle="' + bodyId + '"><span class="grow">' +
        esc(g.name) + ' <span class="k">' + esc(g.description) + '</span>' + phaseHeader(g) +
        '</span>' + badge + '</h2>' +
        '<div class="body' + (gatedOff && !state["phaseopen:" + g.phase] ? " hidden" : "") + '" id="' + bodyId + '">' +
        (mode === "checklist" ? checklistTable(g.steps) : g.steps.map(stepCard).join("")) +
        '</div></div>';
    }).join("");

    const tally = RESULT.summary.counts;
    $("summary").innerHTML = Object.keys(STATE_PILL).filter(k => tally[k]).map(k => {
      const [cls, label] = STATE_PILL[k];
      return '<span><b>' + tally[k] + '</b> <span class="pill ' + cls + '">' + label + '</span></span>';
    }).join("") + '<span class="k">of ' + STEPS.length + ' steps &middot; ' +
      esc(RESULT.summary.status) + '</span>';

    bind();
  }

  function bind() {
    mount.querySelectorAll("[data-set]").forEach(b => {
      b.onclick = () => {
        const [uid, kind] = b.getAttribute("data-set").split(":");
        state.choices[uid] = kind === "pending" ? undefined : kind;
        if (kind === "custom" || kind === "failure") state["open:" + uid] = true;
        save(); draw();
      };
    });
    mount.querySelectorAll("[data-toggle-step]").forEach(b => {
      b.onclick = () => {
        const uid = b.getAttribute("data-toggle-step");
        state["open:" + uid] = !state["open:" + uid];
        save(); draw();
      };
    });
    mount.querySelectorAll("[data-toggle]").forEach(h => {
      h.onclick = e => {
        if (e.target.tagName === "BUTTON") return;
        const el = mount.querySelector("#" + h.getAttribute("data-toggle"));
        if (el) el.classList.toggle("hidden");
        const card = h.closest("[data-phase]");
        if (card) state["phaseopen:" + card.getAttribute("data-phase")] = el && !el.classList.contains("hidden");
      };
    });
    mount.querySelectorAll("[data-custom]").forEach(t => {
      t.onchange = () => { state.custom[t.getAttribute("data-custom")] = t.value; save(); draw(); };
    });
    mount.querySelectorAll("[data-exit]").forEach(inp => {
      inp.onchange = () => { readCustom(inp.getAttribute("data-exit")); save(); draw(); };
    });
    mount.querySelectorAll("[data-status]").forEach(inp => {
      inp.onchange = () => { readCustom(inp.getAttribute("data-status")); save(); draw(); };
    });
    mount.querySelectorAll("[data-status-set]").forEach(b => {
      b.onclick = () => {
        const [uid, s] = b.getAttribute("data-status-set").split(":");
        readCustom(uid);
        state.status[uid] = s;
        save(); draw();
      };
    });
    mount.querySelectorAll("[data-timeout]").forEach(c => {
      c.onchange = () => {
        const uid = c.getAttribute("data-timeout");
        readCustom(uid);
        state.timeout[uid] = c.checked || undefined;
        save(); draw();
      };
    });
    mount.querySelectorAll("[data-eval]").forEach(b => {
      b.onclick = () => {
        const uid = b.getAttribute("data-eval");
        readCustom(uid);
        state["open:" + uid] = true;
        save(); draw();
      };
    });
    mount.querySelectorAll("[data-rest]").forEach(b => {
      b.onclick = () => markRest(b.getAttribute("data-rest"));
    });
  }

  /** Take the pasted output, the exit code and the status off the form as
   *  they stand: pasting and clicking Evaluate never blurs the textarea. */
  function readCustom(uid) {
    const ta = mount.querySelector('[data-custom="' + uid + '"]');
    if (ta) state.custom[uid] = ta.value;
    const exit = mount.querySelector('[data-exit="' + uid + '"]');
    if (exit) {
      const value = String(exit.value).trim();
      state.exit[uid] = /^-?\d+$/.test(value) ? value : "0";
    }
    const status = mount.querySelector('[data-status="' + uid + '"]');
    if (status) {
      const value = String(status.value).trim();
      if (/^\d{3}$/.test(value)) state.status[uid] = value;
    }
  }

  /**
   * Mark this step and every one after it Success.
   *
   * The long tail of an activity is usually commands that simply worked, and
   * clicking Success eighty times is how an operator stops reading. A step
   * someone has already given a verdict is left alone, and so is one the run
   * never reaches.
   */
  function markRest(fromUid) {
    if (fromUid) state.choices[fromUid] = "success";
    const start = fromUid ? STEPS.findIndex(st => st.uid === fromUid) : 0;
    // A verdict can open a path that was closed - a checksum retry loop, a
    // handler - so mark, re-run, and mark whatever became reachable.
    for (let round = 0; round < 25; round++) {
      recompute();
      let changed = false;
      for (let i = Math.max(0, start); i < STEPS.length; i++) {
        const st = STEPS[i];
        if ((st.rt || {}).state !== "pending" || state.choices[st.uid]) continue;
        state.choices[st.uid] = "success";
        changed = true;
      }
      if (!changed) break;
    }
    save(); draw();
  }

  function download(name, text, type) {
    const blob = new Blob([text], { type: type });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = name;
    a.click();
  }
  const fileBase = () => String((META.activity || "mop") + "_" + (META.node || "node")).replace(/[^A-Za-z0-9._-]+/g, "_");

  $("btnRestSuccess").onclick = () => markRest(null);
  const chk = $("chkValidateChecks");
  chk.checked = !!state.validateChecks;
  chk.onchange = () => { state.validateChecks = chk.checked; save(); draw(); };
  const strictBox = $("chkStrict");
  strictBox.checked = !!state.strict;
  strictBox.onchange = () => { state.strict = strictBox.checked; save(); draw(); };
  const hiddenBox = $("chkHidden");
  hiddenBox.checked = !!state.showHidden;
  hiddenBox.onchange = () => { state.showHidden = hiddenBox.checked; save(); draw(); };

  $("btnDebug").onclick = function () {
    state.debug = !state.debug;
    this.textContent = "Debug panels: " + (state.debug ? "on" : "off");
    save(); draw();
  };
  $("btnExpand").onclick = () => {
    for (const st of STEPS) state["open:" + st.uid] = true;
    save(); draw();
  };
  $("btnCollapse").onclick = () => {
    for (const st of STEPS) state["open:" + st.uid] = false;
    save(); draw();
  };
  $("btnReset").onclick = () => {
    if (!confirm("Clear every Success/Failure/Custom on this node?")) return;
    // Keep what is not a verdict: the parameters and the view settings.
    state = Object.assign(blank(), { params: state.params, debug: state.debug,
                                     validateChecks: state.validateChecks, strict: state.strict,
                                     showHidden: state.showHidden });
    save(); draw();
  };
  $("btnExport").onclick = () => {
    recompute();
    download(fileBase() + "_result.json", JSON.stringify(exportResult(), null, 2), "application/json");
  };
  $("btnReport").onclick = () => {
    recompute();
    download(fileBase() + "_EXECUTION_REPORT.html", buildReport(RUNDOC, RESULT, META, doc.lint || []), "text/html");
  };
  $("btnSave").onclick = () => {
    const html = savedCopy();
    if (!html) { alert("This page cannot copy itself."); return; }
    download(fileBase() + "_walked.html", html, "text/html");
  };
  $("btnDebug").textContent = "Debug panels: " + (state.debug ? "on" : "off");

  function exportResult() {
    return {
      node: META, generated: META.generated, exported: new Date().toISOString(),
      params: Object.assign({}, PARAMS, state.params),
      strictEngine: !!state.strict,
      summary: RESULT.summary,
      engineGap: DIVERGE,
      steps: STEPS.map(s => ({
        seq: s.seq, uid: s.uid, id: s.step_id, phase: s.phase, kind: s.kind,
        description: (s.rt || {}).desc || s.description, node: s.node_target,
        command: (s.rt || {}).send || s.send, body: (s.rt || {}).body || undefined,
        choice: state.choices[s.uid] || "pending",
        state: (s.rt || {}).state, note: (s.rt || {}).note || undefined,
        message: (s.rt || {}).messageText || "",
        output: (s.rt || {}).output || "", exitCode: (s.rt || {}).exit,
        httpStatus: s.kind === "rest" ? (s.rt || {}).status : undefined,
        branch: (s.rt || {}).branch || undefined,
        routes: (s.rt || {}).routes && (s.rt || {}).routes.length ? s.rt.routes : undefined,
        handlerOf: (s.rt || {}).handlerOf || undefined,
        checks: ((s.rt || {}).checks || []).map(c => ({ check: c.label, ok: c.ok })),
      })),
      log: RESULT.log,
      finalVariables: RESULT.vars,
    };
  }

  /** The page as it was delivered, with this walk baked in - reopening it
   *  shows exactly this state, on any machine. */
  function savedCopy() {
    if (!doc.pristine) return null;
    const seed = Object.assign({}, doc.seedExtra ? doc.seedExtra() : {},
                               { savedAt: new Date().toISOString().replace(/[^0-9]/g, "").slice(0, 14),
                                 state: JSON.parse(JSON.stringify(state)) });
    delete seed.state.vars;
    // The marker is assembled, never written out whole: this source is itself
    // inside the page being copied, and a literal would match itself.
    const open = "<" + "script type=\"application/json\" id=\"execflow" + "-seed\">";
    const close = "</" + "script>";
    const tag = open + JSON.stringify(seed).replace(/</g, "\\u003c") + close;
    let base = doc.pristine;
    const was = base.lastIndexOf(open);
    if (was >= 0) {
      const end = base.indexOf(close, was);
      if (end >= 0) base = base.slice(0, was) + base.slice(end + close.length);
    }
    // straight after <body>: the page script reads the seed when it runs, so
    // the seed has to be parsed before it
    const body = base.indexOf("<" + "body");
    const at = body < 0 ? -1 : base.indexOf(">", body) + 1;
    return at <= 0 ? tag + base : base.slice(0, at) + tag + base.slice(at);
  }

  renderLint();
  draw();
  return { draw: draw, state: () => state, result: () => RESULT, exportResult: exportResult };
}

/** A seed baked into a saved copy, if this page is one. */
function readSeed() {
  try {
    const el = document.getElementById("execflow-seed");
    return el ? JSON.parse(el.textContent) : null;
  } catch (e) { return null; }
}

if (typeof module !== "undefined" && module.exports) module.exports = { initDocument, readSeed };
