/* ui.js - the document: phases, step cards, the three buttons.
 *
 * One renderer, two pages. A MOP generated by mopgen.py and a workflow the
 * operator has just dropped into the runner are the same thing by the time
 * they get here - a node, a step list, the seed variables, the globals and the
 * request parameters - so they must look and behave identically. Anything else
 * and "it worked in the runner" would say nothing about the document that gets
 * mailed out.
 *
 *     initDocument({mount, meta, steps, vars, globals, params})
 *
 * Every id the page exposes (btnDebug, btnExport, paramGrid, summary, phases,
 * and the data-set / data-custom attributes) is part of the contract
 * test_page_dom.js drives.
 */

function initDocument(doc) {
  const mount = doc.mount || document.body;
  const META = doc.meta || {};
  const STEPS = doc.steps || [];
  const VARS0 = doc.vars || {};
  const GLOBALS = doc.globals || [];
  const PARAMS = doc.params || {};
  const KEY = doc.storageKey || ("execflow:" + META.node + ":" + META.activity);

  let state = load() || { choices: {}, custom: {}, exit: {}, params: {}, debug: false,
                          validateChecks: false };
  state.exit = state.exit || {};

  function load() {
    try { return JSON.parse(localStorage.getItem(KEY) || "null"); } catch (e) { return null; }
  }
  function save() {
    try { localStorage.setItem(KEY, JSON.stringify(state)); } catch (e) { /* private mode */ }
  }

  /* ================================================================= *
   *  Run state
   * ================================================================= */
  function recompute() {
    const vars = Object.assign({}, VARS0, PARAMS, state.params);

    /* A request parameter usually reaches a command through a global, not
       directly - LOCAL_PATH: /mnt/shared_data/${CHILD_REQ_ID}/${NODE_NAME}.
       The globals in VARS0 were resolved against the generation parameters, so
       they are re-derived here in declaration order, the way
       Expander.base_context() establishes them, or editing a parameter in the
       panel changes nothing the operator can see. A parameter always wins over
       a global of the same name, as it does in the expander. */
    const overridden = Object.assign({}, PARAMS, state.params);
    for (const [name, raw] of GLOBALS || []) {
      if (name in overridden) continue;
      vars[name] = (typeof raw === "string") ? interpolate(raw, vars) : raw;
    }

    let halted = false, haltReason = null;

    for (const st of STEPS) {
      const rt = st.rt = { log: [], missing: [], trace: [] };

      if (halted) { rt.state = "notrun"; rt.note = haltReason; continue; }

      const whenOk = evalCond(st.when, vars, rt.trace);
      const skipOn = st.skip_when ? evalCond(st.skip_when, vars, rt.trace) : false;
      rt.send = interpolate(st.send_raw, vars, rt.missing);
      rt.desc = interpolate(st.descriptionRaw || "", vars) || st.description;

      if (!whenOk || skipOn) {
        rt.state = "skipped";
        rt.note = !whenOk ? ("when is false: " + st.when)
                          : ("skip_when is true: " + st.skip_when);
        continue;
      }

      const choice = state.choices[st.uid] || "pending";
      if (choice === "pending") {
        // Not walked yet. Keep the happy path applied so later commands still
        // render with values - the generation-time assumption, carried forward.
        applyRegisters(st.register, st.success_output || "", vars, rt.log);
        for (const k in (st.implied || {})) if (!vars[k]) vars[k] = st.implied[k];
        rt.state = "pending";
        continue;
      }

      const output = choice === "custom" ? (state.custom[st.uid] || "")
                   : choice === "failure" ? (st.failure_output || "")
                   : (st.success_output || "");
      // The exit code is part of the evidence, not a constant. A step whose
      // only criterion is `exit_code: 0` passes on ANY pasted text, so an
      // operator reporting a command that failed needs to be able to say so.
      const exit = choice === "failure" ? 1
                 : choice === "custom" ? parseInt(state.exit[st.uid] || "0", 10)
                 : 0;
      rt.output = output;
      rt.exit = exit;
      applyRegisters(st.register, output, vars, rt.log);
      const crit = (st.validation || {}).successCriteria;
      rt.checks = explainCriteria(crit, vars, output, exit);
      const pass = choice === "failure" ? false
                 : evalCriteria(crit, vars, output, exit);
      rt.state = pass ? "success" : "failure";
      rt.message = pass ? (st.validation || {}).successMessage
                        : (st.validation || {}).failureMessage;
      rt.messageText = interpolate(rt.message || "", vars);

      if (!pass) {
        const of = st.on_failure || { mode: "stop" };
        rt.routed = of.mode === "run" ? ("handler: " + of.step) : of.mode;
        if (of.mode === "stop") {
          halted = true;
          haltReason = "halted at " + st.uid + " (on_failure: stop)";
        }
      }
    }
    state.vars = vars;
    return vars;
  }

  /* ================================================================= *
   *  Render
   * ================================================================= */
  const esc = s => String(s === undefined || s === null ? "" : s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  const STATE_PILL = {
    success: ["p-ok", "SUCCESS"], failure: ["p-bad", "FAILURE"],
    skipped: ["p-idle", "SKIPPED"], notrun: ["p-idle", "NOT EXECUTED"],
    pending: ["p-idle", "pending"], unknown: ["p-warn", "CONDITIONAL"],
  };

  mount.innerHTML =
    '<div class="toolbar">' +
      '<label class="chk" title="Walk the pre/post health checks the way the ' +
        'activity is walked - criteria, custom output and all - instead of ' +
        'ticking OK or NOK">' +
        '<input type="checkbox" id="chkValidateChecks"> Validate pre/post checks' +
      '</label>' +
      '<button id="btnRestSuccess">Rest all Success</button>' +
      '<button id="btnDebug">Debug panels: off</button>' +
      '<button id="btnExpand">Expand all</button>' +
      '<button id="btnCollapse">Collapse all</button>' +
      '<button id="btnReset" class="ghost">Reset run</button>' +
      '<button id="btnExport" class="ghost">Export result JSON</button>' +
      '<span class="grow"></span><span class="sum" id="summary"></span>' +
    '</div>' +
    '<div class="card" id="paramCard">' +
      '<h2 data-toggle="paramBody"><span class="grow">Request parameters</span>' +
      '<span class="k" id="paramCount"></span></h2>' +
      '<div class="body" id="paramBody"><div class="grid" id="paramGrid"></div>' +
      '<div class="k" style="margin-top:8px">Changing a value re-resolves every ' +
      'command below. Values the CIQ supplies are not listed here.</div></div>' +
    '</div>' +
    '<div id="phases"></div>';

  const $ = id => mount.querySelector("#" + id);

  function renderParams() {
    const grid = $("paramGrid");
    const used = {};
    for (const st of STEPS) for (const t of st.consumes || []) used[t] = (used[t] || 0) + 1;
    const names = Object.keys(PARAMS).concat(
      Object.keys(state.params).filter(k => !(k in PARAMS)));
    const extra = [];
    for (const st of STEPS) for (const u of st.unresolved || []) {
      if (!names.includes(u.token) && !extra.includes(u.token) &&
          u.token.indexOf(".") < 0 && u.token.indexOf("base64:") < 0) extra.push(u.token);
    }
    const all = names.concat(extra);
    $("paramCount").textContent = all.length + " parameter" + (all.length === 1 ? "" : "s") +
      (extra.length ? ", " + extra.length + " unresolved" : "");
    grid.innerHTML = all.map(n => {
      const v = (n in state.params) ? state.params[n] : (PARAMS[n] !== undefined ? PARAMS[n] : "");
      const hits = used[n] ? (" · " + used[n] + " step" + (used[n] === 1 ? "" : "s")) : "";
      const miss = !v && extra.includes(n) ? ' class="unres"' : "";
      return '<div><label class="f"' + miss + '>' + esc(n) + esc(hits) + '</label>' +
             '<input type="text" data-param="' + esc(n) + '" value="' + esc(v) + '"></div>';
    }).join("");
    grid.querySelectorAll("input[data-param]").forEach(inp => {
      inp.addEventListener("change", () => {
        state.params[inp.getAttribute("data-param")] = inp.value;
        save(); draw();
      });
    });
  }

  function stepCard(st) {
    const rt = st.rt || {};
    const [cls, label] = STATE_PILL[rt.state] || STATE_PILL.pending;
    const open = state["open:" + st.uid] ? " open" : "";
    const choice = state.choices[st.uid] || "pending";
    const loop = (st.loop_path || []).map(l => l.label).filter(Boolean).join(" / ");

    let h = '<div class="step s-' + rt.state + '" id="c' + st.uid + '">';
    h += '<div class="sh"><span class="seq">' + st.seq + '</span><div class="grow">';
    h += '<div class="sd">' + esc(rt.desc || st.description || st.uid) + '</div>';
    h += '<div class="meta">' + esc(st.node_target || st.node_ref || "local");
    if (loop) h += ' &middot; ' + esc(loop);
    if (st.when) h += ' &middot; when ' + esc(st.when);
    h += '</div></div><span class="pill ' + cls + '">' + label + '</span>';
    h += '<button class="ghost" data-toggle-step="' + st.uid + '">' +
         (open ? "hide" : "detail") + '</button>';
    h += '</div>';

    if (st.send) h += '<div style="padding:0 12px 8px"><pre>' + esc(rt.send || st.send) + '</pre></div>';
    if (st.email) {
      h += '<div style="padding:0 12px 8px"><pre>to: ' + esc(st.email.to) +
           '\nsubject: ' + esc(st.email.subject) + '</pre></div>';
    }

    h += '<div class="btns">';
    h += btn(st.uid, "success", "Success", choice);
    h += btn(st.uid, "failure", "Failure", choice);
    h += btn(st.uid, "custom", "Custom input", choice);
    if (choice !== "pending") {
      h += '<button data-set="' + st.uid + ':pending" class="ghost">clear</button>';
    }
    h += '<button data-rest="' + st.uid + '" class="ghost" title="Mark this step ' +
         'and every one after it Success">Success from here</button>';
    h += '</div>';

    h += '<div class="sbody' + open + '" id="b' + st.uid + '">';
    if (choice === "custom") {
      h += '<label class="f">Paste what the node printed</label>';
      h += '<textarea data-custom="' + st.uid + '">' + esc(state.custom[st.uid] || "") + '</textarea>';
      const code = state.exit[st.uid] === undefined ? "0" : String(state.exit[st.uid]);
      h += '<div class="btns" style="padding:8px 0 0;align-items:center">' +
           '<button data-eval="' + st.uid + '" class="primary">Evaluate</button>' +
           '<label class="f" style="margin:0 0 0 6px">exit code</label>' +
           '<input type="text" class="exit" data-exit="' + st.uid + '" value="' + esc(code) + '">' +
           '<span class="k">what the command returned; 0 is success</span>' +
           '</div>';
      h += verdictPanel(st, rt);
    } else if (choice !== "pending") {
      h += '<label class="f">Output used (' +
           (choice === "success" ? "synthesised from the success criteria"
                                 : "synthesised to fail the criteria") + ')</label>';
      h += '<pre>' + esc(rt.output || "(no output asserted - judged on exit code)") + '</pre>';
    }
    if (rt.messageText) h += '<div class="meta" style="margin-top:6px">' + esc(rt.messageText) + '</div>';
    if (rt.note) h += '<div class="meta" style="margin-top:6px">' + esc(rt.note) + '</div>';
    if (rt.routed) h += '<div class="meta" style="margin-top:6px">on_failure &rarr; ' + esc(rt.routed) + '</div>';

    if (state.debug) h += debugPanel(st, rt);
    h += '</div></div>';
    return h;
  }

  /**
   * Why this step passed or failed, on the evidence given.
   *
   * Shown for pasted output, because that is the only case where the operator
   * did not already know the answer. `exit_code: 0` as the sole criterion is
   * the one that catches people out: any pasted text satisfies it, and without
   * this panel the page just says SUCCESS and looks broken.
   */
  function verdictPanel(st, rt) {
    const checks = rt.checks || [];
    const [cls, label] = STATE_PILL[rt.state] || STATE_PILL.pending;
    let h = '<div class="verdict"><div class="vhead"><span class="pill ' + cls + '">' +
            label + '</span> <span class="k">on the output and exit code you gave</span></div>';
    h += '<ul class="checks">';
    for (const check of checks) {
      h += '<li class="' + (check.ok ? "good" : "bad") + '">' +
           (check.ok ? "\u2713" : "\u2717") + " " + esc(check.label) +
           (check.detail ? ' <span class="k">(' + esc(check.detail) + ')</span>' : "");
      for (const t of check.trace || []) {
        h += '<div class="k">' + esc(t.expr) + " &nbsp; [" +
             esc(t.leftVal === null ? "<unset>" : t.leftVal) + "] vs [" + esc(t.right) +
             "] &rarr; " + (t.result ? "TRUE" : "FALSE") + "</div>";
      }
      for (const child of check.children || []) {
        h += '<div class="k">' + (child.ok ? "\u2713" : "\u2717") + " " +
             esc(child.label) + "</div>";
      }
      h += "</li>";
    }
    h += "</ul>";

    const captured = (rt.log || []).filter(l => l.value !== null && l.value !== undefined);
    const missed = (rt.log || []).filter(l => l.value === null || l.value === undefined);
    if (captured.length) {
      h += '<div class="k" style="margin-top:6px">captured from your output: ' +
           captured.map(l => '<span class="mono">' + esc(l.name) + "=" + esc(l.value) +
                             "</span>").join(", ") + "</div>";
    }
    if (missed.length) {
      h += '<div class="k">nothing matched: ' +
           missed.map(l => '<span class="mono">' + esc(l.name) + "</span>").join(", ") + "</div>";
    }
    if (!(st.register || []).length) {
      h += '<div class="k" style="margin-top:6px">this step captures nothing from its ' +
           "output, so only the exit code decides it</div>";
    }
    return h + "</div>";
  }

  function btn(uid, kind, text, choice) {
    return '<button data-set="' + uid + ':' + kind + '"' +
           (choice === kind ? ' class="on"' : '') + '>' + text + '</button>';
  }

  function debugPanel(st, rt) {
    let h = '<div class="dbg"><b>debug</b>';
    h += row("phase", st.phase + " (" + st.render_mode + ")");
    if (st.node_ref !== st.node_target) h += row("node", st.node_ref + " &rarr; " + esc(st.node_target));
    if (st.send_raw && st.send_raw !== rt.send) h += row("send raw", esc(st.send_raw));
    for (const t of rt.trace || []) {
      h += row("condition", esc(t.expr) + " &nbsp; [" +
               esc(t.leftVal === null ? "<unset>" : t.leftVal) + "] vs [" + esc(t.right) +
               "] &rarr; <b>" + (t.result ? "TRUE" : "FALSE") + "</b>");
    }
    for (const u of st.unresolved || []) {
      h += row("unresolved", '<span class="unres">${' + esc(u.token) + '}</span> &mdash; ' + esc(u.reason));
    }
    for (const l of rt.log || []) {
      h += row("register", esc(l.name) + " = " +
               (l.value === null ? "<i>" + esc(l.source) + "</i>" : esc(l.value)));
    }
    if ((st.consumes || []).length) h += row("consumes", (st.consumes || []).map(esc).join(", "));
    const crit = (st.validation || {}).successCriteria;
    if (crit && Object.keys(crit).length) h += row("criteria", esc(JSON.stringify(crit)));
    if (st.retries) h += row("retries", st.retries + " every " + (st.retry_delay_sec || 0) + "s");
    h += row("on_failure", esc(JSON.stringify(st.on_failure)));
    return h + '</div>';
  }
  function row(k, v) { return '<div class="row"><span>' + k + '</span><span>' + v + '</span></div>'; }

  function checklistTable(steps) {
    let h = '<table><thead><tr><th style="width:44px">#</th><th>Step</th>' +
            '<th>Command</th><th style="width:150px">Expected</th>' +
            '<th style="width:110px">Result</th></tr></thead><tbody>';
    for (const st of steps) {
      const rt = st.rt || {};
      const [cls, label] = STATE_PILL[rt.state] || STATE_PILL.pending;
      h += '<tr><td class="k">' + st.seq + '</td>';
      h += '<td>' + esc(rt.desc || st.description) + '<div class="k">' +
           esc(st.node_target || "") + '</div></td>';
      h += '<td class="cmd">' + esc(rt.send || st.send || (st.email ? "send mail" : "")) + '</td>';
      h += '<td class="k">' + esc((st.validation || {}).description || "") + '</td>';
      h += '<td><span class="pill ' + cls + '">' + label + '</span>' +
           '<div class="btns" style="padding:4px 0 0">' +
           '<button data-set="' + st.uid + ':success" class="' +
             (state.choices[st.uid] === "success" ? "on" : "") + '">OK</button>' +
           '<button data-set="' + st.uid + ':failure" class="' +
             (state.choices[st.uid] === "failure" ? "on" : "") + '">NOK</button>' +
           '</div></td></tr>';
    }
    return h + '</tbody></table>';
  }

  function draw() {
    recompute();
    renderParams();

    const groups = [];
    for (const st of STEPS) {
      const last = groups[groups.length - 1];
      if (!last || last.phase !== st.phase) {
        groups.push({ phase: st.phase, name: st.phase_name,
                      description: st.phase_description, mode: st.render_mode, steps: [st] });
      } else last.steps.push(st);
    }

    $("phases").innerHTML = groups.map((g, i) => {
      const counts = {};
      for (const st of g.steps) {
        const s = (st.rt || {}).state || "pending";
        counts[s] = (counts[s] || 0) + 1;
      }
      const badge = Object.keys(counts).map(k => {
        const [cls, label] = STATE_PILL[k] || STATE_PILL.pending;
        return '<span class="pill ' + cls + '">' + counts[k] + ' ' + label + '</span>';
      }).join(" ");
      const bodyId = "ph" + i;
      // "Validate pre/post checks" promotes the checklist phases to the same
      // treatment the activity gets: real criteria, pasted output, the verdict
      // panel. OK/NOK is a faster read when the checks are a formality, and the
      // wrong tool when one of them is what the change hinges on.
      const mode = state.validateChecks ? "interactive" : g.mode;
      return '<div class="card"><h2 data-toggle="' + bodyId + '"><span class="grow">' +
        esc(g.name) + ' <span class="k">' + esc(g.description) + '</span></span>' + badge + '</h2>' +
        '<div class="body" id="' + bodyId + '">' +
        (mode === "checklist" ? checklistTable(g.steps) : g.steps.map(stepCard).join("")) +
        '</div></div>';
    }).join("");

    const tally = {};
    for (const st of STEPS) {
      const s = (st.rt || {}).state || "pending";
      tally[s] = (tally[s] || 0) + 1;
    }
    $("summary").innerHTML = Object.keys(STATE_PILL).filter(k => tally[k]).map(k => {
      const [cls, label] = STATE_PILL[k];
      return '<span><b>' + tally[k] + '</b> <span class="pill ' + cls + '">' + label + '</span></span>';
    }).join("") + '<span class="k">of ' + STEPS.length + ' steps</span>';

    bind();
  }

  function bind() {
    mount.querySelectorAll("[data-set]").forEach(b => {
      b.onclick = () => {
        const [uid, kind] = b.getAttribute("data-set").split(":");
        state.choices[uid] = kind === "pending" ? undefined : kind;
        if (kind === "custom") state["open:" + uid] = true;
        save(); draw();
      };
    });
    mount.querySelectorAll("[data-toggle-step]").forEach(b => {
      b.onclick = () => {
        const uid = b.getAttribute("data-toggle-step");
        state["open:" + uid] = !state["open:" + uid];
        save(); draw();
      };
    });
    mount.querySelectorAll("[data-toggle]").forEach(h => {
      h.onclick = e => {
        if (e.target.tagName === "BUTTON") return;
        const el = mount.querySelector("#" + h.getAttribute("data-toggle"));
        if (el) el.classList.toggle("hidden");
      };
    });
    mount.querySelectorAll("[data-custom]").forEach(t => {
      t.onchange = () => { state.custom[t.getAttribute("data-custom")] = t.value; save(); draw(); };
    });
    mount.querySelectorAll("[data-exit]").forEach(inp => {
      inp.onchange = () => { readCustom(inp.getAttribute("data-exit")); save(); draw(); };
    });
    mount.querySelectorAll("[data-eval]").forEach(b => {
      b.onclick = () => {
        const uid = b.getAttribute("data-eval");
        readCustom(uid);
        state["open:" + uid] = true;
        save(); draw();
      };
    });
    mount.querySelectorAll("[data-rest]").forEach(b => {
      b.onclick = () => markRest(b.getAttribute("data-rest"));
    });
  }

  /** Take the pasted output and the exit code off the form as they stand.
   *  A `change` event has not necessarily fired: pasting and clicking
   *  Evaluate straight through never blurs the textarea. */
  function readCustom(uid) {
    const ta = mount.querySelector('[data-custom="' + uid + '"]');
    if (ta) state.custom[uid] = ta.value;
    const exit = mount.querySelector('[data-exit="' + uid + '"]');
    if (exit) {
      const value = String(exit.value).trim();
      state.exit[uid] = /^-?\d+$/.test(value) ? value : "0";
    }
  }

  /**
   * Mark this step and every one after it Success.
   *
   * The long tail of an activity is usually commands that simply worked, and
   * clicking Success eighty times is how an operator stops reading. A step
   * someone has already given a verdict is left alone - this fills in the
   * rest, it does not overwrite a decision.
   */
  function markRest(fromUid) {
    let reached = !fromUid;
    for (const st of STEPS) {
      if (!reached) {
        if (st.uid !== fromUid) continue;
        reached = true;
        state.choices[st.uid] = "success";
        continue;
      }
      if ((st.rt || {}).state === "skipped") continue;
      if (state.choices[st.uid]) continue;
      state.choices[st.uid] = "success";
    }
    save(); draw();
  }

  $("btnRestSuccess").onclick = () => markRest(null);
  const chk = $("chkValidateChecks");
  chk.checked = !!state.validateChecks;
  chk.onchange = () => { state.validateChecks = chk.checked; save(); draw(); };

  $("btnDebug").onclick = function () {
    state.debug = !state.debug;
    this.textContent = "Debug panels: " + (state.debug ? "on" : "off");
    save(); draw();
  };
  $("btnExpand").onclick = () => {
    for (const st of STEPS) state["open:" + st.uid] = true;
    save(); draw();
  };
  $("btnCollapse").onclick = () => {
    for (const st of STEPS) state["open:" + st.uid] = false;
    save(); draw();
  };
  $("btnReset").onclick = () => {
    if (!confirm("Clear every Success/Failure/Custom on this node?")) return;
    // Keep what is not a verdict: the parameters, the debug toggle and the
    // pre/post-check mode are settings, not results. `exit` must survive as an
    // object either way - recompute reads state.exit[uid] on every custom step.
    state = { choices: {}, custom: {}, exit: {}, params: state.params,
              debug: state.debug, validateChecks: state.validateChecks };
    save(); draw();
  };
  $("btnExport").onclick = () => {
    recompute();
    const out = {
      node: META, generated: META.generated, exported: new Date().toISOString(),
      params: Object.assign({}, PARAMS, state.params),
      steps: STEPS.map(s => ({
        seq: s.seq, uid: s.uid, phase: s.phase,
        description: (s.rt || {}).desc || s.description, node: s.node_target,
        command: (s.rt || {}).send || s.send, choice: state.choices[s.uid] || "pending",
        state: (s.rt || {}).state, message: (s.rt || {}).messageText || "",
        output: (s.rt || {}).output || "", exitCode: (s.rt || {}).exit,
        checks: ((s.rt || {}).checks || []).map(c => ({ check: c.label, ok: c.ok })),
      })),
      finalVariables: state.vars,
    };
    const blob = new Blob([JSON.stringify(out, null, 2)], { type: "application/json" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = (META.activity || "mop") + "_" + META.node + "_result.json";
    a.click();
  };
  $("btnDebug").textContent = "Debug panels: " + (state.debug ? "on" : "off");

  draw();
  return { draw: draw, state: () => state };
}

if (typeof module !== "undefined" && module.exports) module.exports = { initDocument };
